version: '2'

services:
  web:
    image: nginx:latest
    container_name: prepaid-card
    ports:
        - "8080:80"
    working_dir: /app/curve
    volumes:
          - .:/app/curve
          - ~/.ssh/id_rsa:/root/.ssh/id_rsa
          - ~/.ssh/known_hosts:/root/.ssh/known_hosts
          - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

  php:
    image: php:7-fpm
    volumes:
        - .:/app/curve

  redis:
    image: redis:4
    container_name: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./.data/:/data
